"""add cover_url to books

Revision ID: 1c36b0fcf9b1
Revises: becdf4fe960a
Create Date: 2025-06-27 14:28:58.115733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c36b0fcf9b1'
down_revision = 'becdf4fe960a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
