"""Rename name to username in users table

Revision ID: becdf4fe960a
Revises: 0c34b88c567c
Create Date: 2025-06-26 00:57:23.943061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becdf4fe960a'
down_revision = '0c34b88c567c'
branch_labels = None
depends_on = None


def upgrade():
    # Add new column
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))

    # Copy data from `name` to `username`
    op.execute("UPDATE users SET username = name")

    # Now safely drop `name`
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###